### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by BathoryPeter** [mueschel/OsmcToSVG#1]
I have some modifications locally, and in order to publish them, a license need to be added here.

Thanks for the script!
Péter

**Comment by mueschel** [comment]
You're right. The project doesn't contain much original code so that I didn't care about a license yet. I'll think about it in the next days.
However, I'd really appreciate if you made a pull request for any additions you did!

**Comment by mueschel** [comment]
I decided to publish the code under a free CC0 license - however, a link back to this repository would be highly appreciated.
